spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useSSL=true
    username: root
    password: Dove0926
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
mybatis:
  mapperLocations: classpath:com/cathychen/ApplicationPortal/mapper/*.xml
  typeAliasesPackage: cn.boot.domain
logging:
  level:
    root: info